### ISSUE TITLE
Suggestion: Use `--readonly` flag to use Ilastik project from multiple processed

### ISSUE THREAD

**Issue by votti** [ElementoLab/imcpipeline#1]
https://github.com/ElementoLab/imcpipeline/blob/34dbe05d952661401d460c1f9e5635bb9dc4bbc3/imcpipeline/pipeline.py#L452

Using the `--readonly` flag in the command line does make copying the project file obsolete.

**Comment by afrendeiro** [comment]
Thanks for the tip!
